version: "3"
services:
    erigon:
        image: ghcr.io/ledgerwatch/erigon:latest
        container_name: erigon-bsc
        command: >
            --chain=bsc
            --http
            --http.addr=0.0.0.0
            --http.port=8545
            --http.corsdomain="*"
            --http.api=debug,web3,net,eth,txpool
            --ws
            --ws.addr=0.0.0.0
            --ws.port=8546
            --ws.api=debug,web3,net,eth,txpool
            --prune=10
            --fastsync
            --maxpeers=50
        volumes:
            - ./erigon-data:/root/.local/share/erigon
        ports:
            - "8545:8545" # HTTP port
            - "8546:8546" # WebSocket port
            - "30303:30303"
            - "30303:30303/udp"
        restart: always
